### ISSUE TITLE
PortentaH7 WiFi can you explain why it doesn't work on the M4 core

### ISSUE THREAD

**Issue by hpssjellis** [khoih-prog/Portenta_H7_AsyncWebServer#1]
Does Wifi, BLE, and Ethernet not work on the M4 core from a hardware issue?

@khoih-prog  I love your libraries which I just found today. I am the maker of the [portenta-pro-community-solutions](https://github.com/hpssjellis/portenta-pro-community-solutions) library. My twitter is aka [rocksetta](https://twitter.com/rocksetta) and I would really like to connect somehow.   

I have not had much luck making the Portneta WiFi, BLE and Ethernet Async so I will check out this library. I recently posted on the Arduino mbed core a similar question  

https://github.com/arduino/ArduinoCore-mbed/issues/360

Keep up the great work!

**Comment by khoih-prog** [comment]
Hi @hpssjellis 

I'm really **impressed** with what you've done with Portenta_H7, especially [**my-examples-for-the-arduino-portentaH7**](https://github.com/hpssjellis/my-examples-for-the-arduino-portentaH7) and ML.

I actually haven't tried WiFi, BLE or Ethernet on M4 core. But **IMHO**, if they can run on M7, I guess, they can run on M4 (via M7, using RPC, if necessary) as most of the work are done in the related (WiFi, BLE or Ethernet) chip. I'm possibly wrong as I haven't spend time to investigate the issue at all. I also **don't know** if those tasks consume so much M7 MPU time to prevent you to run ML, can you test and verify?

Can you also use M4 for certain jobs in ML?

I have to look at what you've achieved so far to avoid unnecessary duplication, and it'll take some time to digest.

Glad that you can use any of my libraries. Keep in touch.

Best Regards,

**Comment by hpssjellis** [comment]
Great to connect @khoih-prog. I am in BC looks like you are in Ontario. To avoid Portenta duplication I have been summarizing all my work at: 

https://github.com/hpssjellis/maker100

I teach High School Robotics but the plan is to make a basic Robotics / Machine Learning course for all University students not just CS and Engineer students.  I am guessing you are connected with a university.


Yes, M4 can do ML but it is slower. Problem with testing code for ML is that it takes a long time to compile the first run ~ 25 minutes (much faster on Linux) so testing all kinds of WiFi and BLE with an ML program is a multi-hour project. Your work should make that much easier.

**Comment by khoih-prog** [comment]
Hi @hpssjellis 

Just invite you to my [**Portenta_H7_Private** repo](https://github.com/khoih-prog/Portenta_H7_Private) for further discussions as here is not the right place for general Portenta_H7 issues.
